### ISSUE TITLE
Usage example for shell prompt

### ISSUE THREAD

**Issue by woopla** [mafredri/zsh-async#17]
Hello,

I have a shell prompt which shows the status of my git repos. Problem is, I now have a large repo where git status takes an inordinate amount of time, making the prompt unbearably slow.

`zsh-async` looks like the right solution, but I can't get it to work when the background job is a zsh function itself. Here's some example code:
```zsh
setopt prompt_subst

async_init

async_start_worker lprompt -n

lprompt_complete() {
    PS1="> $3"
    zle && zle reset-prompt
}

async_register_callback lprompt lprompt_complete

PS1=''

function foo() {
    echo "foo "
}

function precmd() {
    async_job lprompt foo
}
```

This works fine when the last line is `async_job lprompt echo "foo "`, so I know the rest of the code works fine. I also tried:
- `async_job lprompt $(foo)`
- `async_job lprompt '$(foo)'`

How do I get this to work?

This problem I have is probably ignorance on my part, rather than a bug in `zsh-async` :smile_cat:

Thanks,

Clément

**Comment by mafredri** [comment]
It looks like all you need to do is start the worker a bit later. All functions that you want to use must be defined **before** starting the worker. The reason for this is that the worker is essentially a fork of your shell at the point in time when it is started, it will not receive future updates from the environment.

If you need to pass new state into the worker, try sending them as parameters to the function.

Hope this helps 😄!

**Comment by woopla** [comment]
Thanks! This fixes the `foo` case, but not when replacing `$(foo)` by the Oh-My-ZSH-provided `git_prompt_info` function.

Running `git_prompt_info` by itself outputs the expected prompt string to stdout, so I don't know what's going on. The last command in that function is a `printf`, so its output should be in $3 but an `echo $@` shows it's empty.

**Comment by mafredri** [comment]
Does `git_prompt_info` exist when you start the worker via `async_start_worker lprompt -n`?

For example, updating your example with:

```zsh
git_prompt_info
async_start_worker lprompt -n
```

Works? If not, then oh-my-zsh must be initialized before the worker is started.

All that aside. I think I noticed one problem. An example:

```zsh
get_prompt_info() {
    cd -q $1         # Enter the current directory
    git_prompt_info  # Print git info
}

async_start_worker lprompt -n

async_job lprompt get_prompt_info $PWD
```

Here I tried to demonstrate that you must pass state into the worker. Now we're calling `get_prompt_info` with `$PWD` as an argument so that it can enter the correct directory.

PS. `cd -q` prevents `cd` from triggering side-effects in zsh (e.g. chpwd hooks).

**Comment by woopla** [comment]
Passing $PWD did the trick, thanks a ton! On to modifying `RPROMPT` to be asynchronous too, and I'll be the happiest person on earth for the next five minutes :rofl:

**Comment by mafredri** [comment]
Glad you got it working 😄! Btw, there's no need to make the RPROMPT async if it doesn't bother you that it pops up later, e.g. `RPROMPT='$(sleep 1 && echo hi)'` will work without disrupting the regular prompt 👍!

**Comment by von** [comment]
> It looks like all you need to do is start the worker a bit later. All functions that you want to use must be defined **before** starting the worker. 

So glad I found this issue. I suggest adding a note to the `zsh-async/README.md` about functions having to be defined before the worker is created.

**Comment by mafredri** [comment]
@von It is mentioned in the [Usage](https://github.com/mafredri/zsh-async#usage)-section but in very different words, so I can understand this fact isn't conveyed appropriately. If you'd like to take a stab at making this point clearer in the readme, I'd be happy to accept a PR. Perhaps it would make sense to have it mentioned in both usage and the documentation for the `async_start_worker` function?
