### ISSUE TITLE
Can't call function: command not found

### ISSUE THREAD

**Issue by tastytea** [mafredri/zsh-async#56]
I'm trying to get this to work:

``` zsh
function completed_callback() { print $@ } 
function foo() { print hello }

async_init
async_start_worker my_worker -n
async_register_callback my_worker completed_callback
async_job my_worker foo
```

But I always get `foo 127 0.0350267887 (eval):1: command not found: foo 0` back.

zsh 5.8.1, zsh-async master branch, installed with antibody

**Comment by mafredri** [comment]
Could you share the output from running `setopt` in terminal?

Also, would you mind trying it out by putting the following in a file (e.g. `test.zsh`) and executing it?

```
#!/usr/bin/env zsh

emulate -R zsh

source async.zsh

function completed_callback() { print $@ } 
function foo() { print hello }

async_init
async_start_worker my_worker -n
async_register_callback my_worker completed_callback
async_job my_worker foo

sleep 0.1
sleep 0.1
```

Then:

```
chmod +x test.zsh
./test.zsh
```

**Comment by tastytea** [comment]
> Could you share the output from running `setopt` in terminal?

```
alwaystoend
autocd
autopushd
completeinword
correctall
extendedhistory
noflowcontrol
histexpiredupsfirst
histignoredups
histignorespace
histverify
interactive
interactivecomments
longlistjobs
monitor
promptsubst
pushdignoredups
pushdminus
sharehistory
shinstdin
zle
```


> Also, would you mind trying it out by putting the following in a file (e.g. `test.zsh`) and executing it?
> […]

That works.

**Comment by tastytea** [comment]
Hmm. I have the snippet from the first comment in my `.zshrc`.  It used to fail every time. Then it worked sometimes and failed sometimes.  Now it works all the time. It seems that the problem is in my Zsh configuration somewhere. Sorry for bothering you with this.
