### ISSUE TITLE
Passing function argument with spaces

### ISSUE THREAD

**Issue by anishathalye** [mafredri/zsh-async#8]
Is there any way to pass an async job a single argument with spaces in it?

Here's a minimal failing test case:

```bash
source ./async.zsh
async_init

COMPLETED=0
show_result() {
	COMPLETED=$((COMPLETED + 1))
	echo "$3"
}

async_start_worker worker -n
async_register_callback worker show_result

# works as expected
echo "a:1 2"
async_job worker echo "b:1 2"

# doesn't work as expected
echo "c:1        2"
async_job worker echo "d:1        2"

while ((COMPLETED < 2)); do
	echo "Waiting..."
	sleep 0.1
done
```

Expected output:

```
a:1 2
c:1        2
Waiting...
b:1 2
d:1        2
```

Actual output:

```
a:1 2
c:1        2
Waiting...
b:1 2
d:1 2
```

I think this is a real issue, even in pure: the async job `cd`s to `$*` ([see here](https://github.com/sindresorhus/pure/blob/master/pure.zsh#L235)), but that's not correct if the path is something like `/a/b  c`, for example. (I haven't actually tried pure myself, but I think it will fail with an example like this)

**Comment by mafredri** [comment]
Thanks for opening the issue providing a test case!

I've been somewhat aware of this limitation but I haven't put much effort into fixing it, seeing as this is coming up now, I guess I should :).

Regarding pure, a single space in a directory will work, but multiple spaces would indeed break it. Definitely got to fix this.

**Comment by mafredri** [comment]
@anishathalye I just pushed a new branch [`lossless-arguments`](https://github.com/mafredri/zsh-async/tree/lossless-arguments) that should fix your issue. I'd appreciate it if you can try it out =).

In fact it's a big improvement, not just spaces, but newlines are now considered as well.

The only thing I'm unhappy about is that I had to use a magic string (`___ZSH_ASNYC_EOC___`) as a separator to signify the end of command parameters :/.

**Comment by anishathalye** [comment]
Oh cool, it seems to be working for me now! (Don't need to use this [workaround](https://github.com/anishathalye/dotfiles/blob/218a58d88c9bd4fa965b418849beac9d3c5dab68/zsh/prompt.zsh#L257) anymore...)

**Comment by mafredri** [comment]
Thanks for testing, haven't run into any problems locally either so I'll push it :)
